import Head from 'next/head'

import { HeaderBar } from 'components/headerBar';
import { useSignInState } from '@/src/contexts/signInStateProvider';

import { RecipeChangeForm } from '@/components/recipeChangeForm';

export default function Home() {
  const { user } = useSignInState()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderBar />
      <RecipeChangeForm />
    </>
  )
}
